[theme]
primaryColor = "#7C5CFC"
backgroundColor = "#090B12"
secondaryBackgroundColor = "#0E111B"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
